FROM thomasvn3.jfrog.io/ubi-7/ubi7:7.9

# CAUTION: Removing these libraries will break `yum` and other packages
# RUN rpm -e --nodeps glib2 \
#                     python \
#                     python-libs \
#                     openssl-libs
