services:
  web-dvwa:
    image: vulnerables/web-dvwa
    container_name: web-dvwa
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    cap_add:
      - ALL
  php-ldap:
    image: vulnerables/phpldapadmin-remote-dump
    container_name: php-ldap
    ports:
      - "8081:80"
